// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tegrczsitmyzpzzgeicv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlZ3JjenNpdG15enB6emdlaWN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MjIxNDMsImV4cCI6MjA2NzA5ODE0M30.DBZr9JfqjGa7WnuWea-h-nU7k9MdOpuoPoVvJT8IFBQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});